### ISSUE TITLE
Dependency not found: Cannot resolve org.apache.flink:flink-connector-kinesis_2.11:1.6.2

### ISSUE THREAD

**Issue by lpiedade** [aws-samples/amazon-kinesis-analytics-taxi-consumer#1]
Maven could not find the library. Are you using another repository or some other version for flink-connector-kinesis?

![image](https://user-images.githubusercontent.com/510345/69544235-10bf1980-0f6e-11ea-9ca7-2688f7832063.png)

**Comment by sthm** [comment]
Unfortunately, the Flink connector for Kinesis is not available from Maven Central. You need to build it yourself. You can follow the steps to [Build the Flink Kinesis Connector](https://aws.amazon.com/blogs/big-data/build-and-run-streaming-applications-with-apache-flink-and-amazon-kinesis-data-analytics-for-java-applications/) with maven. Or you can use this [CloudFormation template](https://github.com/aws-samples/amazon-kinesis-analytics-taxi-consumer/blob/master/cfn-templates/flink-kinesis-connector-build-pipeline.yml) which will build it for you.

Starting with Flink 1.10 the connector will be included in Maven Central.
