### ISSUE TITLE
Map is empty -- the wmsUrl not working

### ISSUE THREAD

**Issue by racheliurui** [aws-samples/amazon-kinesis-analytics-taxi-consumer#2]
Existing WMSUrl 
https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
it gives me empty background 

I tried this one, and it works. 
http://a.tile.openstreetmap.org/{z}/{x}/{y}.png

This one also works.
http://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png

Not sure what's the reason that it's not showing maps via https protocol (any firewall or rules ?)

**Comment by sthm** [comment]
Thanks for letting us know! I've changed the URL as proposed and the dashboard is now working correctly again.
